<?php
/**
 * Tracking template
 *
 * @var $block \Targetbay\Tracking\Block\Tracking
 */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$trackingHelper = $objectManager->get('Targetbay\Tracking\Helper\Data');

$_productInfo = $block->getProductInfo();
$_userInfo = $block->getUserInfo();
$_productStatusInfo = $block->getProductStockInfo();
$visitorName = \Targetbay\Tracking\Helper\Data::ANONYMOUS_USER;

$pageVisitData = '';
$pageVisitUrl = '';
$trackingTypeVal = '';
$_productName = '';
$_productId = '';
$_productImage = '';
$_productUrl = '';
$_userId = '';
$_userEmail = '';
$_userName = '';
if (isset($_productInfo) && !empty($_productInfo)) {
    $_productId = $_productInfo['product_id'] ? $_productInfo['product_id'] : '';
    $_productName = $_productInfo['product_name'] ? $_productInfo['product_name'] : '';
    $_productImage = $_productInfo['product_image'] ? $_productInfo['product_image'] : '';
    $_productUrl = $_productInfo['product_url'] ? $_productInfo['product_url'] : '';
}

if (isset($_userInfo)) {
    $_userId = $_userInfo['user_id'] ? $_userInfo['user_id'] : '';
    $_userEmail = $_userInfo['user_email'] ? $_userInfo['user_email'] : '';
    $_userName = $_userInfo['user_name'] ? $_userInfo['user_name'] : $visitorName;
}
$requestInterface = $objectManager->get('Magento\Framework\App\RequestInterface');
$controllerName = $requestInterface->getControllerName();
if ($controllerName == "product") {
    $pageVisitUrl = $trackingHelper->getApiUrl();
    $pageVisitData = $trackingHelper->getPageInfo();
}

$hostUrl = $trackingHelper->getHostname();
$apiToken = $trackingHelper->getApiToken();
$apiKey = $trackingHelper->getApiIndex();
$moduleVersion = $trackingHelper->getModuleVersion();
$apiStatus = $trackingHelper->getApiStatus();
$trackingEnabled = $trackingHelper->trackingEnabled();

if ($trackingEnabled) :
    $trackingScript = $trackingHelper->getTrackingScript();
    if ($trackingScript) {
        $trackingCode = $trackingScript;
    } else {
        $trackingCode = 'tbTrack: true,
			 tbMessage: true,
			 tbReview: {
				tbSiteReview: true,	
				tbProductReview: true,
				tbBulkReview: true,
				tbQa: true
				}';
    }
    ?>

    <div id="targetbay_message"></div>
    <div id="targetbay_site_reviews"></div>
    <?php echo $block->getOrderId();?>
    <script type="text/javascript">
        tbConfig = {
            apiStatus: '<?php echo $apiStatus;?>',
            apiKey: '<?php echo $apiKey;?>',
            apiToken: '<?php echo $apiToken;?>',
            apiUrl: '<?php echo $hostUrl;?>',
            apiVersion: 'v2',
            trackingType: '1',
            moduleVersion: '<?php echo $moduleVersion;?>',
            productName: '<?php echo $block->escapeQuote($_productName); ?>',
            productId: '<?php echo $_productId; ?>',
            productImageUrl: '<?php echo $_productImage; ?>',
            productUrl: '<?php echo $_productUrl; ?>',
            productStockStatus: '<?php echo $this->getStockAvaliability(); ?>', 
            childProduct: '<?php echo $this->getProductStockInfo(); ?>',
            userId: '<?php echo $_userId; ?>',
            userMail: '<?php echo $_userEmail; ?>',
            userName: '<?php echo $_userName; ?>',
            userAvatar: '',
            pageUrl: '<?php echo $pageVisitUrl;?>',
            pageData: '<?php echo json_encode($pageVisitData);?>',
            <?php echo $trackingCode; ?>
        };
        (function (d, u, tb) {
            var s = d.scripts[0],
                i = u.length, g;
            while (i--) {
                g = d.createElement('script');
                g.src = 'https://' + tb.apiStatus + '.targetbay.com/js/tb-' + u[i] + '.js';
                g.type = 'text/javascript';
                g.async = 'true';
                s.parentNode.insertBefore(g, s);
            }
        })(document, 
            ['track'], 
            tbConfig
        );
    </script>
<?php endif; ?>
<?php $siteReviewSnippets = $trackingHelper->getSiteReviewSnippets();?>
<?php if (!empty($siteReviewSnippets) && $siteReviewSnippets['average_score'] > 0): ?>
<div itemscope itemtype="http://schema.org/Organization">
    <div itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
        <span itemprop="bestRating" content="5"></span> 
        <span itemprop="ratingValue" content="<?php echo $siteReviewSnippets['average_score']; ?>"></span> 
        <span itemprop="reviewCount" content="<?php echo $siteReviewSnippets['reviews_count']; ?>"></span>
        <span itemprop="ratingCount" content="<?php echo $siteReviewSnippets['reviews_count']; ?>"></span>
    </div>
    <?php if ($siteReviewSnippets['reviews_count'] > 0): ?> 
    <?php foreach ($siteReviewSnippets['reviews']  as $key => $aggregateReviewDetails): ?>
        <?php $reviewId = $aggregateReviewDetails->_id; ?>
        <?php $reviewTitle = $aggregateReviewDetails->_source->title; ?>
        <?php $review = $aggregateReviewDetails->_source->message; ?>
        <?php $timestamp = $aggregateReviewDetails->_source->timestamp; ?>
        <?php $reviewRating = $aggregateReviewDetails->_source->review_rating; ?>
        <?php $userName = $aggregateReviewDetails->_source->user_name; ?>

        <div itemprop="review" id="<?php echo $block->escapeHtml($reviewTitle) . '-' . $key; ?>" 
            itemscope itemtype="http://schema.org/Review" data-reviewid="<?php echo $reviewId; ?>">
            <span itemprop="name" content="<?php echo $block->escapeHtml($reviewTitle); ?>"></span> 
            <span itemprop="description" content="<?php echo $block->escapeHtml($review); ?>"></span> 
            <span itemprop="datePublished" content="<?php echo date('m/d/Y', $timestamp); ?>"></span>
            <div itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                <span itemprop="ratingValue" content="<?php echo $reviewRating; ?>"></span>
                <span itemprop="worstRating" content="1"></span>
                <span itemprop="bestRating" content="5"></span>
            </div>
            <div itemprop="author" itemscope itemtype="http://schema.org/Thing">
                <span itemprop="name" content="<?php echo $userName; ?>"></span>
            </div>
        </div>
    <?php  endforeach; ?>
    <?php endif; ?>
</div>
<?php endif; ?>