<?php
/**
 * Tracking template
 *
 * @var $block \Targetbay\Tracking\Block\Product\Richsnippets
 */
?>
<?php
$richSnippets = $block->getProductReviews();
$richSnippetsType = $block->getSnippetType();
?>
<?php if ($richSnippetsType > 0) { ?>
<?php if (!empty($richSnippets) && $richSnippets['average_score'] > 0): ?>
	<span itemprop="aggregateRating" itemscope itemtype= "http://schema.org/AggregateRating">
	    <span itemprop="bestRating" content="5"></span> 
	    <span itemprop="worstRating" content="1"></span> 
	    <span itemprop="ratingValue" content="<?php echo $richSnippets['average_score']; ?>"></span> 
	    <span itemprop="reviewCount" content="<?php echo $richSnippets['reviews_count']; ?>"></span>
	    <span itemprop="ratingCount" content="<?php echo $richSnippets['reviews_count']; ?>"></span>
	</span>

	<?php if ($richSnippets['reviews_count'] > 0): ?>
	<?php foreach ($richSnippets['reviews']  as $key => $aggregateReviewDetails): ?>
	<?php $reviewId = $aggregateReviewDetails->_id; ?>
	<?php $reviewTitle = $aggregateReviewDetails->_source->review_title; ?>
	<?php $review = $aggregateReviewDetails->_source->review; ?>
	<?php $timestamp = $aggregateReviewDetails->_source->timestamp; ?>
	<?php $reviewRating = $aggregateReviewDetails->_source->review_rating; ?>
	<?php $userName = $aggregateReviewDetails->_source->user_name; ?>
	<div itemprop="review" id="<?php echo $block->escapeHtml($reviewTitle) . '-' . $key; ?>" itemscope itemtype="http://schema.org/Review" data-reviewid="<?php echo $reviewId; ?>">
	        <span itemprop="name" content="<?php echo $block->escapeHtml($reviewTitle); ?>"></span> 
	        <span itemprop="description" content="<?php echo $block->escapeHtml($review); ?>"></span> 
	        <span itemprop="datePublished" content="<?php echo date('m/d/Y', $timestamp); ?>"></span>
		<div itemprop="itemReviewed" itemscope itemtype="http://schema.org/Thing">
			<span itemprop="name" content="<?php echo $block->getEscapedProductName(); ?>"></span>
		</div>
		<?php if ($reviewRating > 0): ?>
		<div itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
	        <span itemprop="ratingValue" content="<?php echo $reviewRating; ?>"></span> 
	        <span itemprop="worstRating" content="1"></span>
	        <span itemprop="bestRating" content="5"></span>
		</div>
		<?php endif; ?>
		<div itemprop="author" itemscope itemtype="http://schema.org/Thing">
	        <span itemprop="name" content="<?php echo $userName; ?>"></span>
		</div>
	</div>
	<?php endforeach; ?>
	<?php endif; ?>
<?php endif; ?>
<?php } ?>